### ISSUE TITLE
Create a new data submission guide page utilizing existing MD files/repo

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/documentation#38]
We want to create a new data submission page in the documents website that will live here: https://docs.sennetconsortium.org/data-submission

Another team has already created MD files with the information regarding data submission: https://github.com/hubmapconsortium/data_submission_guide

- [x] Fork the existing repo to X Atlas Consortia
- [x] Create a unique table of contents for this page that will link out to each `section`. Should look like this 
<img width="284" alt="image" src="https://github.com/sennetconsortium/documentation/assets/7218802/ba4b9f83-a07f-486b-b743-6f1dccd1a1ec">

**Comment by libpitt** [comment]
<img width="1321" alt="Screen Shot 2024-01-26 at 9 05 56 AM" src="https://github.com/sennetconsortium/documentation/assets/115558393/28baa18b-0f67-4055-9dea-a9beaf3a3248">
<img width="1345" alt="Screen Shot 2024-01-26 at 9 06 10 AM" src="https://github.com/sennetconsortium/documentation/assets/115558393/64324a6c-d1db-4a61-b179-8d2067e7fdb1">


Note had to add 
```
---
layout: default
---
```
to each md file in order to see it rendered locally in the docker container that mimics GH pages. I may have seen it work without the tag when on the actual GH pages server, but I am not sure. 

Due to the name of the files, the url path names may not be the most SEO friendly.
